# Site settings
author: dwane richards
title: Code Life 20/20
header-img: img/home-bg.png
email: dwanerich@gmail.com
copyright_name: dwane richards
description: > # this means to ignore newlines until "baseurl:"
  sky is never the limit. our vision's are.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  dwanerich

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
